import { useState } from "react";
import ShareButtons from "../components/ShareButtons";
import ToolsNav from "../components/ToolsNav";
import { usePageTitle } from "../hooks/usePageTitle";

const CATEGORIES = {
  bug: { label: "Bug Report", fields: ["Summary", "Steps to Reproduce", "Expected Behavior", "Actual Behavior", "Environment", "Screenshots / Logs", "Severity"] },
  feature: { label: "Feature Request", fields: ["Summary", "Use Case", "Proposed Solution", "Alternatives Considered", "Business Impact", "Priority"] },
  billing: { label: "Billing Issue", fields: ["Account Email", "Issue Summary", "Invoice / Transaction ID", "Amount in Question", "Preferred Resolution"] },
  access: { label: "Access / Permissions", fields: ["User Email", "Issue Summary", "Current Access Level", "Requested Access Level", "Business Justification", "Approved By"] },
  general: { label: "General Inquiry", fields: ["Subject", "Description", "Relevant Details", "Preferred Contact Method"] },
  onboarding: { label: "Onboarding Request", fields: ["New User Name", "Email", "Role / Department", "Access Needed", "Start Date", "Special Requirements"] },
};

function generateTemplate(category, companyName, includeInternalFields) {
  const cat = CATEGORIES[category];
  if (!cat) return "";
  const company = companyName || "Your Company";
  const lines = [`# ${cat.label} — ${company}`, ""];
  lines.push(`**Category:** ${cat.label}`);
  lines.push(`**Date:** ${new Date().toLocaleDateString()}`);
  lines.push(`**Submitted by:** [Name / Email]`);
  lines.push("");
  lines.push("---");
  lines.push("");
  for (const field of cat.fields) {
    lines.push(`## ${field}`);
    lines.push(`[Enter ${field.toLowerCase()} here]`);
    lines.push("");
  }
  if (includeInternalFields) {
    lines.push("---");
    lines.push("");
    lines.push("## Internal Fields (Agent Use Only)");
    lines.push("");
    lines.push("**Assigned to:** [Agent name]");
    lines.push("**Priority:** [P1 / P2 / P3 / P4]");
    lines.push("**SLA deadline:** [Date/Time]");
    lines.push("**Internal notes:** [Notes]");
    lines.push("");
  }
  lines.push("---");
  lines.push(`*Template generated by DoAide Support*`);
  return lines.join("\n");
}

export default function TicketTemplateGeneratorPage() {
  usePageTitle("Free Ticket Template Generator — Create Support Ticket Forms");
  const [category, setCategory] = useState("bug");
  const [companyName, setCompanyName] = useState("");
  const [includeInternal, setIncludeInternal] = useState(false);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);

  const handleGenerate = () => {
    setResult(generateTemplate(category, companyName.trim(), includeInternal));
  };

  const handleCopy = async () => {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(result);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* noop */ }
  };

  return (
    <div className="tool-page">
      <ToolsNav />
      <main className="tool-main">
        <div className="tool-container">
          <h1 className="tool-title">Ticket Template Generator</h1>
          <p className="tool-subtitle">
            Generate structured support ticket templates for your team — bug reports, feature requests, billing issues, and more. No sign-up required.
          </p>

          <div className="calc-card">
            <label className="calc-label">
              Ticket Category
              <select className="calc-input" value={category} onChange={(e) => setCategory(e.target.value)}>
                {Object.entries(CATEGORIES).map(([key, val]) => (
                  <option key={key} value={key}>{val.label}</option>
                ))}
              </select>
            </label>
            <label className="calc-label">
              Company Name (optional)
              <input className="calc-input" value={companyName} onChange={(e) => setCompanyName(e.target.value)} placeholder="e.g. Acme Inc" />
            </label>
            <label style={{ display: "flex", alignItems: "center", gap: "0.5rem", fontSize: "0.9rem", color: "var(--color-text)", cursor: "pointer" }}>
              <input type="checkbox" checked={includeInternal} onChange={(e) => setIncludeInternal(e.target.checked)} />
              Include internal agent fields
            </label>
            <button className="btn btn-primary" onClick={handleGenerate}>Generate Template</button>
          </div>

          {result && (
            <div className="calc-card">
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <h2 style={{ margin: 0, fontSize: "1.1rem", fontWeight: 700, color: "var(--color-text)" }}>
                  Generated Template
                </h2>
                <button className="btn btn-primary" style={{ padding: "0.35rem 0.75rem", fontSize: "0.8rem" }} onClick={handleCopy}>
                  {copied ? "Copied!" : "Copy Markdown"}
                </button>
              </div>
              <pre style={{
                margin: 0, padding: "1rem", background: "var(--color-bg)", border: "1px solid var(--color-border)",
                borderRadius: "8px", fontSize: "0.82rem", lineHeight: 1.6, color: "var(--color-text-secondary)",
                whiteSpace: "pre-wrap", wordBreak: "break-word", overflowX: "auto", maxHeight: "500px",
              }}>
                {result}
              </pre>
              <ShareButtons path="/tools/ticket-template" text="Generate support ticket templates instantly — free tool by DoAide Support" />
            </div>
          )}

          <section className="tool-info">
            <h2>Why Ticket Templates Matter</h2>
            <p>
              Structured ticket templates ensure customers provide all the information agents need upfront.
              This reduces back-and-forth, speeds up resolution, and improves first-contact resolution rates
              by 25-35%.
            </p>
            <h3>Best Practices</h3>
            <ul>
              <li>Use category-specific templates to capture the right details</li>
              <li>Include required vs optional fields to reduce friction</li>
              <li>Add internal fields for agent triage and routing</li>
              <li>Review and update templates quarterly based on common gaps</li>
            </ul>
          </section>

          <div className="calc-card" style={{ textAlign: "center" }}>
            <p style={{ fontSize: "0.9rem", color: "var(--color-text-secondary)", marginBottom: "0.75rem" }}>Want dynamic ticket forms with auto-routing and SLA tracking?</p>
            <a href="/register" className="btn btn-primary" style={{ display: "inline-block", textDecoration: "none" }}>Sign up free</a>
          </div>
        </div>
      </main>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebApplication",
            name: "Ticket Template Generator",
            description: "Generate structured support ticket templates for bug reports, feature requests, and billing issues — free, no sign-up required.",
            url: "https://support.doaide.com/tools/ticket-template",
            applicationCategory: "BusinessApplication",
            operatingSystem: "Web",
            offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
            author: { "@type": "Organization", name: "Apprend Technologies", url: "https://doaide.com" },
          }),
        }}
      />
    </div>
  );
}
